name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    # https://developer.garmin.com/downloads/connect-iq/sdks/connectiq-sdk-win-3.1.6-2019-10-23-2de4665c6.zip
    - name: Install Connect IQ SDK
      run: |
        echo Downloading SDK
        curl https://developer.garmin.com/downloads/connect-iq/sdks/connectiq-sdk-win-3.1.6-2019-10-23-2de4665c6.zip > sdk.zip
        sudo apt install zip
        unzip sdk.zip -d ~/sdk
        export PATH=$PATH:~/sdk/bin

